name: Mod Build

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

env:
  HAXE_VER: 4.3.7

jobs:
  buildAndroid:
    name: Build Android
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: ${{ env.HAXE_VER }}

      - name: Install Libraries
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: modBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
          